# HTTP 连接配置 TODO
ok:
  http:
    connect-timeout: 30
    keep-alive-duration: 300
    max-idle-connections: 200
    read-timeout: 30
    write-timeout: 30

server:
  shutdown: graceful

clay:
  business:
    topic:
      name: clayBusiness
    # GrayLog ip 地址 TODO
    graylog:
      ip: 192.168.21.6
    upload:
      crowd:
        path: /temp
    log:
      topic:
        name: clayLog
  # 数据库相关的信息配置 TODO
  database:
    ip: 127.0.0.1
    port: 3306
    username: root
    password: 123456
  # kafka相关的信息配置 TODO
  kafka:
    ip: 120.24.68.134
    port: 9092
  redis:
    host: 120.24.68.134
    port: 6379
    password: clay
  xxl:
   job:
     admin:
      ip: 192.168.21.6
      port: 19003
      username: root
      password: 123456
     executor:
       appname: clay # 执行器 AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册
       jobHandlerName: clayJob # 执行器任务名

spring:
  datasource:
    url: jdbc:mysql://${clay.database.ip}:${clay.database.port}/clay?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: ${clay.database.username}
    password: ${clay.database.password}
    driver-class-name: com.mysql.jdbc.Driver
  # kafka相关的信息配置 TODO
  kafka:
    bootstrap-servers: ${clay.kafka.ip}:${clay.kafka.port}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto:
        offset:
          reset: earliest
      auto-commit-interval: 1000
      enable-auto-commit: true
  jpa:
    show-sql: true
  # redis 相关配置 TODO
  redis:
    host: ${clay.redis.host}
    port: ${clay.redis.port}
    password: ${clay.redis.password}


# 监控配置  TODO
management:
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true

# apollo  TODO
app:
  id: clay
apollo:
  bootstrap:
    enabled: true
    namespaces: boss.clay,dynamic-tp-apollo-dtp.yml

# xxl job TODO
xxl:
  job:
    admin:
      addresses: http://${clay.xxl.job.admin.ip}:${clay.xxl.job.admin.port}/xxl-job-admin # 调度中心部署跟地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；
      username: ${clay.xxl.job.admin.username} # 后台用户名
      password: ${clay.xxl.job.admin.password}# 后台密码
    executor:
      appname: ${clay.xxl.job.executor.appname}# 执行器 AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册
      jobHandlerName: ${clay.xxl.job.executor.jobHandlerName} # 执行器任务名
      ip: # 执行器IP [选填]：默认为空表示自动获取IP，多网卡时可手动设置指定IP，该IP不会绑定Host仅作为通讯实用；地址信息用于 "执行器注册" 和 "调度中心请求并触发任务"；
      port: 6666 # ### 执行器端口号 [选填]：小于等于0则自动获取；默认端口为9999，单机部署多个执行器时，注意要配置不同执行器端口；
      logpath: logs/xxl # 执行器运行日志文件存储磁盘路径 [选填] ：需要对该路径拥有读写权限；为空则使用默认路径；
      logretentiondays: 30 # 执行器日志文件保存天数 [选填] ： 过期日志自动清理, 限制值大于等于3时生效; 否则, 如-1, 关闭自动清理功能；
    accessToken:  # 执行器通讯TOKEN [选填]：非空时启用；

##################### wx mp config #####################
weixin:
  mp:
    account:
      appid:
      secret:
      token:
      aesKey:



